import org.restlet.*;
import org.restlet.data.Protocol;
import org.restlet.resource.*;
import org.restlet.routing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Benedikt
 */
public class Uebung_04_RestService extends ServerResource {
    
    public static void main(String[] args) throws Exception {
        //new Server(Protocol.HTTP, 8182, Uebung_04_RestService.class).start();
        new Server(Protocol.HTTP, 8182, new Uebung_04_RestService().createInboundRoot()).start();
    }
    
    @Get  
   public String toString() {  
      return "hello, world";  
   }
   
    public Restlet createInboundRoot() {
        Router router = new Router(getContext());

        // Serve the files generated by the GWT compilation step.
        router.attachDefault(new Directory(getContext(), "war:///"));
        //router.attach("/contacts/123", Uebung_04_RestService.class);
        router.attach("/toString/", Uebung_04_RestService.class);
        return router;
    }
}
